services:
  db:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ${PWD}/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql:ro
      - db:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db: